/* ---------------------------------------------------- */
/*  SCHEME "ALQUILER":                		            */
/*  DDL,DML and DCL statements to  create the  schema   */
/*  called alquiler. Prototype for a rent cars system.  */
/* ---------------------------------------------------- */


--TABLE SPACES CREATED FOR "ALQUILER" SCHEME.

CREATE TABLESPACE DEF_ALQ
DATAFILE '/u01/app/oracle/oradata/XE/def_alquiler.dbf' --CHANGE THIS TO YOUR ACTUAL PATH
SIZE 2M
AUTOEXTEND ON;

CREATE TEMPORARY TABLESPACE TMP_ALQ
TEMPFILE '/u01/app/oracle/oradata/XE/tmp_alquiler.dbf' --CHANGE THIS TO YOUR ACTUAL PATH
SIZE 2M
AUTOEXTEND ON; --YOU CAN EXECUTE "SELECT TABLESPACE_NAME FROM DBA_TABLESPACES;" TO CHECK.


--"ALQUILER" SCHEME CREATION AND TABLESPACE ASIGNATION.

CREATE USER ALQUILER
IDENTIFIED BY alquiler
DEFAULT TABLESPACE DEF_ALQ
TEMPORARY TABLESPACE TMP_ALQ
QUOTA 2M ON DEF_ALQ;

GRANT CONNECT,RESOURCE TO ALQUILER WITH ADMIN OPTION;
GRANT CREATE PUBLIC SYNONYM TO ALQUILER;
GRANT CREATE USER TO ALQUILER;
GRANT CREATE ROLE TO ALQUILER;


--DB CONNECTION WITH "ALQUILER".

CONN ALQUILER/alquiler;


--TABLES CREATION, BEGIN DDL.

CREATE TABLE REGSERVICIO
(
  K_REGISTRO NUMBER(5) NOT NULL 
, K_MATRICULA VARCHAR2(6) NOT NULL 
, K_TALLER NUMBER(3) NOT NULL 
, K_SERVICIO NUMBER(3) NOT NULL 
, F_INGRESO DATE NOT NULL 
, F_SALIDA DATE
, V_SERVICIO NUMBER(10, 2)
, CONSTRAINT REGSERVICIO_PK PRIMARY KEY 
  (
    K_REGISTRO 
  )
  ENABLE 
);

CREATE TABLE TALLER 
(
  K_TALLER NUMBER(3) NOT NULL 
, N_TALLER VARCHAR2(50) NOT NULL 
, O_DIRECCION VARCHAR2(50) NOT NULL 
, O_TELEFONO VARCHAR2(15) NOT NULL 
, N_ESPECIALIDAD VARCHAR2(20) NOT NULL
, N_RESPONSABLE VARCHAR2(20) NOT NULL 
, CONSTRAINT TALLER_PK PRIMARY KEY 
  (
    K_TALLER 
  )
  ENABLE 
);

CREATE TABLE RESERVA 
(
  K_RESERVA NUMBER(10) NOT NULL 
, K_NIT NUMBER(12) NOT NULL 
, K_AGENCIA NUMBER NOT NULL 
, F_RESERVA DATE NOT NULL 
, V_TOTAL NUMBER(10, 2) NOT NULL 
, CONSTRAINT RESERVA_PK PRIMARY KEY 
  (
    K_RESERVA 
  )
  ENABLE 
);

CREATE TABLE RESERVA_VEHICULO 
(
  K_RESERVA NUMBER(10) NOT NULL 
, K_MATRICULA VARCHAR2(6) NOT NULL 
, F_INICIO DATE NOT NULL 
, F_FIN DATE NOT NULL 
, V_PRECIO_ALQUILER NUMBER(10, 2) NOT NULL 
, V_LITROS_GASOLINA NUMBER(3, 1) NOT NULL 
, I_ENTREGADO VARCHAR2(1) NOT NULL 
, CONSTRAINT RESERVA_VEHICULO_PK PRIMARY KEY 
  (
    K_RESERVA 
  , K_MATRICULA 
  )
  ENABLE 
);

CREATE TABLE CLIENTE 
(
  K_NIT NUMBER(12) NOT NULL 
, K_NITREF NUMBER(12) 
, N_NOMCLIENTE VARCHAR2(20) NOT NULL 
, N_APECLIENTE VARCHAR2(20) NOT NULL 
, O_DIRECCION VARCHAR2(50) NOT NULL 
, O_TELEFONO VARCHAR2(12) NOT NULL 
, CONSTRAINT CLIENTE_PK PRIMARY KEY 
  (
    K_NIT 
  )
  ENABLE 
);

CREATE TABLE SERVICIO 
(
  K_SERVICIO NUMBER(3) NOT NULL 
, N_SERVICIO VARCHAR2(30) NOT NULL 
, CONSTRAINT SERVICIO_PK PRIMARY KEY 
  (
    K_SERVICIO 
  )
  ENABLE 
);

CREATE TABLE SERVICIOXTALLER 
(
  K_TALLER NUMBER(3) NOT NULL 
, K_SERVICIO NUMBER(3) NOT NULL 
, CONSTRAINT TALLER_SERVICIO_PK PRIMARY KEY 
  (
    K_TALLER 
  , K_SERVICIO 
  )
  ENABLE 
);

CREATE TABLE VEHICULO 
(
  K_MATRICULA VARCHAR2(6) NOT NULL 
, N_COLOR VARCHAR2(15) NOT NULL 
, N_MARCA VARCHAR2(15) NOT NULL 
, I_DISPONIBLE VARCHAR2(1) NOT NULL 
, CONSTRAINT VEHICULO_PK PRIMARY KEY 
  (
    K_MATRICULA 
  )
  ENABLE 
);

CREATE TABLE AGENCIA 
(
  K_AGENCIA NUMBER NOT NULL 
, N_AGENCIA VARCHAR2(20) NOT NULL 
, CONSTRAINT AGENCIA_PK PRIMARY KEY 
  (
    K_AGENCIA
  )
  ENABLE
);


--SEQUENCES CREATION.

CREATE SEQUENCE RESERVA_SEQ
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOCYCLE;


--FOREIGN KEY CONSTRAINTS.

ALTER TABLE REGSERVICIO
ADD CONSTRAINT REGSERVICIO_VEHICULO_FK FOREIGN KEY
(
  K_MATRICULA
)
REFERENCES VEHICULO
(
  K_MATRICULA
)
ENABLE;

ALTER TABLE RESERVA
ADD CONSTRAINT RESERVA_AGENCIA_FK FOREIGN KEY
(
  K_AGENCIA
)
REFERENCES AGENCIA
(
  K_AGENCIA
)
ENABLE;

ALTER TABLE RESERVA_VEHICULO
ADD CONSTRAINT RESERVA_VEHICULO_RESERVA_FK FOREIGN KEY
(
  K_RESERVA
)
REFERENCES RESERVA
(
  K_RESERVA
)
ENABLE;

ALTER TABLE RESERVA_VEHICULO
ADD CONSTRAINT RESERVA_VEHICULO_VEHICULO_FK FOREIGN KEY
(
  K_MATRICULA
)
REFERENCES VEHICULO
(
  K_MATRICULA
)
ENABLE;


ALTER TABLE SERVICIOXTALLER
ADD CONSTRAINT SERVICIOXTALLER_SERVICIO_FK FOREIGN KEY
(
  K_SERVICIO
)
REFERENCES SERVICIO
(
  K_SERVICIO
)
ENABLE;

ALTER TABLE SERVICIOXTALLER
ADD CONSTRAINT SERVICIOXTALLER_TALLER_FK FOREIGN KEY
(
  K_TALLER
)
REFERENCES TALLER
(
  K_TALLER
)
ENABLE;

ALTER TABLE RESERVA
ADD CONSTRAINT RESERVA_CLIENTE_FK FOREIGN KEY
(
  K_NIT
)
REFERENCES CLIENTE
(
  K_NIT
);

ALTER TABLE CLIENTE
ADD CONSTRAINT CLIENTE_CLIENTER_FK FOREIGN KEY
(
  K_NITREF
)
REFERENCES CLIENTE
(
  K_NIT
);

ALTER TABLE REGSERVICIO
ADD CONSTRAINT REGSERVICIO_SERVICIOXTALLER_FK FOREIGN KEY
(
  K_TALLER,
  K_SERVICIO
)
REFERENCES SERVICIOXTALLER
(
  K_TALLER,
  K_SERVICIO
);


--CHECK CONSTRAINTS.

ALTER TABLE TALLER
ADD CONSTRAINT N_ESPECIALIDAD_CHK CHECK
(N_ESPECIALIDAD IN ('MECANICA', 'LATONERIA', 'PINTURA', 'ELECTRICIDAD'))
ENABLE;

ALTER TABLE CLIENTE
ADD CONSTRAINT CK_CLIENTEREF CHECK
(K_NITREF NOT LIKE K_NIT);

ALTER TABLE RESERVA_VEHICULO
ADD CONSTRAINT CK_F_INICIO_FIN CHECK
(F_INICIO <= F_FIN);

ALTER TABLE RESERVA_VEHICULO
ADD CONSTRAINT CK_V_PRECIO_ALQUILER CHECK
(V_PRECIO_ALQUILER>=0);

ALTER TABLE VEHICULO
ADD CONSTRAINT CK_I_DISPONIBLE CHECK
(I_DISPONIBLE IN ('S','N'));


--OTHER CONSTRAINTS.

ALTER TABLE TALLER
MODIFY
(
  N_ESPECIALIDAD NULL
);

ALTER TABLE TALLER
ADD
(
  O_EMAIL VARCHAR2(30) NOT NULL
);


--DOCUMENTATION COMMENTS ON COLUMNS.

COMMENT ON COLUMN REGSERVICIO.K_REGISTRO IS 'Codigo del registro';

COMMENT ON COLUMN REGSERVICIO.K_MATRICULA IS 'Matricula del vehiculo';

COMMENT ON COLUMN REGSERVICIO.K_TALLER IS 'Código del taller';

COMMENT ON COLUMN REGSERVICIO.K_SERVICIO IS 'Codigo del servicio';

COMMENT ON COLUMN REGSERVICIO.F_INGRESO IS 'Fecha del  ingreso al taller';

COMMENT ON COLUMN REGSERVICIO.F_SALIDA IS 'Fecha de salida del vehiculo del taller';

COMMENT ON COLUMN REGSERVICIO.V_SERVICIO IS 'Valor del servicio';

COMMENT ON COLUMN TALLER.K_TALLER IS 'Codigo del taller';

COMMENT ON COLUMN TALLER.N_TALLER IS 'Nombre del taller';

COMMENT ON COLUMN TALLER.O_DIRECCION IS 'Direccion del taller';

COMMENT ON COLUMN TALLER.O_TELEFONO IS 'Numero de telefono del taller';

COMMENT ON COLUMN TALLER.N_ESPECIALIDAD IS 'Especialidad (MECANICA,ELECTRICIDAD,LATONERIA Y PINTURA)';

COMMENT ON COLUMN TALLER.N_RESPONSABLE IS 'Nombre del responsable';

COMMENT ON COLUMN RESERVA.K_RESERVA IS 'Numero de reserva';

COMMENT ON COLUMN RESERVA.K_NIT IS 'Nit del cliente que hace la reserva';

COMMENT ON COLUMN RESERVA.K_AGENCIA IS 'Agencia en la que se hace la reserva';

COMMENT ON COLUMN RESERVA.F_RESERVA IS 'Fecha en que se realiza la reserva';

COMMENT ON COLUMN RESERVA.V_TOTAL IS 'Valor total de la reserva';

COMMENT ON COLUMN RESERVA_VEHICULO.K_RESERVA IS 'Codigo de la reserva';

COMMENT ON COLUMN RESERVA_VEHICULO.K_MATRICULA IS 'Codigo de la matricula';

COMMENT ON COLUMN RESERVA_VEHICULO.F_INICIO IS 'Fecha de inicio de la reserva para cada vehiculo';

COMMENT ON COLUMN RESERVA_VEHICULO.F_FIN IS 'Fecha fin reserva para cada vehiculo';

COMMENT ON COLUMN RESERVA_VEHICULO.V_PRECIO_ALQUILER IS 'Precio de alquiler';

COMMENT ON COLUMN RESERVA_VEHICULO.V_LITROS_GASOLINA IS 'Litros de gasolina';

COMMENT ON COLUMN RESERVA_VEHICULO.I_ENTREGADO IS 'Indicador de entregado';

COMMENT ON COLUMN CLIENTE.K_NIT IS 'Numero de identificacion';

COMMENT ON COLUMN CLIENTE.K_NITREF IS 'Identificacion del cliente que lo referencia';

COMMENT ON COLUMN CLIENTE.N_NOMCLIENTE IS 'Nombre';

COMMENT ON COLUMN CLIENTE.N_APECLIENTE IS 'Apellido';

COMMENT ON COLUMN CLIENTE.O_DIRECCION IS 'Direccion';

COMMENT ON COLUMN CLIENTE.O_TELEFONO IS 'Numero de telefono';

COMMENT ON COLUMN SERVICIO.K_SERVICIO IS 'Codigo del servicio';

COMMENT ON COLUMN SERVICIO.N_SERVICIO IS 'Nombre del servicio';

COMMENT ON COLUMN SERVICIOXTALLER.K_TALLER IS 'Codigo del taller';

COMMENT ON COLUMN SERVICIOXTALLER.K_SERVICIO IS 'Codigo del servicio';

COMMENT ON COLUMN VEHICULO.K_MATRICULA IS 'Numero de matricula';

COMMENT ON COLUMN VEHICULO.N_COLOR IS 'Color';

COMMENT ON COLUMN VEHICULO.N_MARCA IS 'Marca';

COMMENT ON COLUMN VEHICULO.I_DISPONIBLE IS 'Indicador de disponibilidad';

COMMENT ON COLUMN AGENCIA.K_AGENCIA IS 'Codigo de la agencia';

COMMENT ON COLUMN AGENCIA.N_AGENCIA IS 'Nombre de la agencia';


--DOCUMENTATION COMMENTS ON TABLES.

COMMENT ON TABLE  REGSERVICIO IS 'Tabla que contiene el registro de los servicios prestados a cada vehiculo';

COMMENT ON TABLE  REGSERVICIO IS 'Tabla que contiene el registro de los servicios prestados a cada vehiculo, contando con la fecha de ingreso y salida del servicio y el taller donde fue recibido';

COMMENT ON TABLE TALLER IS 'Esta tabla contiene los datos básicos de los talleres que la agencia tiene asociados para realizar el chequeo a los vehículos';

COMMENT ON TABLE SERVICIO IS 'Aquí están contenidos los datos sobre los servicios que ofrece el taller a los vehículos';

COMMENT ON TABLE CLIENTE IS 'En la tabla cliente, irán almacenados sus datos básicos (nit, nombre, apellido, dir)';

COMMENT ON TABLE RESERVA IS 'Están almacenados los datos de las reservas de vehículos que realiza el cliente a la agencia';

COMMENT ON TABLE AGENCIA IS 'Se guardan los datos de la agencia';

COMMENT ON TABLE VEHICULO IS 'Aquí están almacenados los datos básicos de los vehículos que tiene la agencia para el alquiler';

COMMENT ON TABLE RESERVA_VEHICULO IS 'Tabla de rompimiento entre la tabla VEHICULO y la tabla RESERVA';

COMMENT ON TABLE SERVICIOXTALLER IS 'Tabla de rompimiento entre la tabla SERVICIO y la tabla TALLER';--END DDL


--INSERT ON TABLES, BEGIN DML.

INSERT ALL         
  INTO AGENCIA (K_AGENCIA,N_AGENCIA) VALUES (100,'AGENCIA NORTE')
  INTO AGENCIA (K_AGENCIA,N_AGENCIA) VALUES (200,'AGENCIA CENTRO')
  INTO AGENCIA (K_AGENCIA,N_AGENCIA) VALUES (300,'AGENCIA SUR')
SELECT * FROM dual;

INSERT ALL
  INTO CLIENTE VALUES (123,null,'Luis','Gonzalez','Cra 4 25 68',7685911)
  INTO CLIENTE VALUES (456,123,'Maria','Santos','Calle 3 65-28',6453321)
  INTO CLIENTE VALUES (789,123,'Juan','Torres','Cra 65 47-56',5336723)
  INTO CLIENTE VALUES (987,789,'Pablo','Rojas','Calle 25 67-34',4433445)
  INTO CLIENTE VALUES (777,789,'Sergio','Henao','Cra 24 77-26',1234567)
SELECT * FROM DUAL;

INSERT ALL
  INTO VEHICULO VALUES ('CIU123','Rojo','Chevrolet','N')
  INTO VEHICULO VALUES ('XYZ456','Azul','Renault','S')
  INTO VEHICULO VALUES ('ABC789','Gris','Kia','N')
  INTO VEHICULO VALUES ('DAE222','Azul','Hyundai','S')
  INTO VEHICULO VALUES ('MCZ381','Gris','Sandero','S')
SELECT * FROM DUAL;

INSERT INTO RESERVA VALUES (RESERVA_SEQ.NEXTVAL,123,100,TO_DATE('09/09/2019','DD/MM/YYYY'),30000);

INSERT INTO RESERVA VALUES (RESERVA_SEQ.NEXTVAL,456,100,TO_DATE('09/09/2019','DD/MM/YYYY'),50000);

INSERT INTO RESERVA VALUES (RESERVA_SEQ.NEXTVAL,123,200,TO_DATE('10/09/2019','DD/MM/YYYY'),180000);

INSERT INTO RESERVA VALUES (RESERVA_SEQ.NEXTVAL,777,200,TO_DATE('10/09/2019','DD/MM/YYYY'),1000000);

INSERT ALL
  INTO RESERVA_VEHICULO VALUES (1,'CIU123',TO_DATE('09/09/2019','DD/MM/YYYY'),TO_DATE('09/09/2019','DD/MM/YYYY'), 30000,5,'S')
  INTO RESERVA_VEHICULO VALUES (2,'XYZ456',TO_DATE('09/09/2019','DD/MM/YYYY'),TO_DATE('09/09/2019','DD/MM/YYYY'), 50000,5,'S')
  INTO RESERVA_VEHICULO VALUES (3,'CIU123',TO_DATE('10/09/2019','DD/MM/YYYY'),TO_DATE('11/09/2019','DD/MM/YYYY'), 30000,3,'N')
  INTO RESERVA_VEHICULO VALUES (3,'ABC789',TO_DATE('10/09/2019','DD/MM/YYYY'),TO_DATE('11/09/2019','DD/MM/YYYY'), 150000,10,'N')
  INTO RESERVA_VEHICULO VALUES (4,'MCZ381',TO_DATE('10/09/2019','DD/MM/YYYY'),TO_DATE('21/09/2019','DD/MM/YYYY'), 1000000,10,'N')
SELECT * FROM DUAL;--END DML


--SECURITY POLICY, BEGIN DCL.

CREATE PUBLIC SYNONYM MANTENIMIENTO FOR REGSERVICIO;

--CREATING FIVE USERS.
CREATE USER U_CLIENTE1
IDENTIFIED BY u_cliente1
DEFAULT TABLESPACE DEF_ALQ
TEMPORARY TABLESPACE TMP_ALQ
QUOTA 2M ON DEF_ALQ
PASSWORD EXPIRE;

CREATE USER U_CLIENTE2
IDENTIFIED BY u_cliente2
DEFAULT TABLESPACE DEF_ALQ
TEMPORARY TABLESPACE TMP_ALQ
QUOTA 2M ON DEF_ALQ
PASSWORD EXPIRE;

CREATE USER U_AUXILIAR1
IDENTIFIED BY u_auxiliar1
DEFAULT TABLESPACE DEF_ALQ
TEMPORARY TABLESPACE TMP_ALQ
QUOTA 2M ON DEF_ALQ
PASSWORD EXPIRE;

CREATE USER U_MANTENIMIENTO1
IDENTIFIED BY u_mantenimiento1
DEFAULT TABLESPACE DEF_ALQ
TEMPORARY TABLESPACE TMP_ALQ
QUOTA 2M ON DEF_ALQ
PASSWORD EXPIRE;

CREATE USER U_ADMINISTRADOR
IDENTIFIED BY u_administrador
DEFAULT TABLESPACE DEF_ALQ
TEMPORARY TABLESPACE TMP_ALQ
QUOTA 2M ON DEF_ALQ
PASSWORD EXPIRE;

--CREATING FOUR ROLES AND ASSIGNING THEM TO USERS.
CREATE ROLE R_CLIENTE_ALQ;
GRANT CONNECT TO R_CLIENTE_ALQ;
GRANT SELECT ON CLIENTE TO R_CLIENTE_ALQ;

CREATE ROLE R_AUX_RESERVAS;
GRANT CONNECT TO R_AUX_RESERVAS;
GRANT INSERT,SELECT,UPDATE,DELETE ON CLIENTE TO R_AUX_RESERVAS;
GRANT SELECT ON RESERVA TO R_AUX_RESERVAS;
GRANT SELECT ON VEHICULO TO R_AUX_RESERVAS;
GRANT SELECT ON AGENCIA TO R_AUX_RESERVAS;

CREATE ROLE R_AUX_MANTENIMIENTO;
GRANT CONNECT TO R_AUX_MANTENIMIENTO;
GRANT INSERT,SELECT,UPDATE,DELETE ON TALLER TO R_AUX_MANTENIMIENTO;
GRANT INSERT,SELECT,UPDATE,DELETE ON SERVICIO TO R_AUX_MANTENIMIENTO;
GRANT SELECT ON RESERVA TO R_AUX_MANTENIMIENTO;

CREATE ROLE R_ADMINISTRADOR;
GRANT CONNECT TO R_ADMINISTRADOR;
GRANT INSERT,SELECT,UPDATE,DELETE ON AGENCIA TO R_ADMINISTRADOR;
GRANT INSERT,SELECT,UPDATE,DELETE ON VEHICULO TO R_ADMINISTRADOR;

GRANT R_CLIENTE_ALQ TO U_CLIENTE1,U_CLIENTE2;
GRANT R_AUX_RESERVAS TO U_AUXILIAR1;
GRANT R_AUX_MANTENIMIENTO TO U_MANTENIMIENTO1;
GRANT R_ADMINISTRADOR TO U_ADMINISTRADOR;