SET SERVEROUTPUT ON
SET VERIFY OFF

CREATE OR REPLACE TRIGGER TG_CAMBIAR_NOMBRE
    BEFORE UPDATE OR INSERT OF N_NOMCLIENTE,N_APECLIENTE ON CLIENTE
    FOR EACH ROW
BEGIN
	IF UPDATING THEN
		IF :NEW.N_NOMCLIENTE<>:OLD.N_NOMCLIENTE THEN
			:NEW.N_NOMCLIENTE:=UPPER(:NEW.N_NOMCLIENTE);
		END IF;
		IF :NEW.N_APECLIENTE<>:OLD.N_APECLIENTE THEN
			:NEW.N_APECLIENTE:=UPPER(:NEW.N_APECLIENTE);
		END IF;
	ELSE
		:NEW.N_NOMCLIENTE:=UPPER(:NEW.N_NOMCLIENTE);
		:NEW.N_APECLIENTE:=UPPER(:NEW.N_APECLIENTE);
	END IF;
END TG_CAMBIAR_NOMBRE;
/