CREATE OR REPLACE PROCEDURE PR_REPORTE_RESERVAS(PK_RESERVA reserva.k_reserva%TYPE)
AS
    CURSOR C_VEHICULO  IS
       SELECT K_MATRICULA,I_ENTREGADO
       FROM RESERVA_VEHICULO
       WHERE K_RESERVA=LK_RESERVA;
    LK_RESERVA RESERVA.K_RESERVA%TYPE:=&LK_RESERVA;
    LN_NOMCOMPLETO CLIENTE.N_NOMCLIENTE%TYPE;
    LC_ERROR INTEGER;
    LM_ERROR VARCHAR(50);
    LV_TOTAL RESERVA.V_TOTAL%TYPE;
    LV_PROMEDIO RESERVA.V_TOTAL%TYPE;
BEGIN
    PR_BUSCAR_CLIENTE(LK_RESERVA,LN_NOMCOMPLETO,LC_ERROR,LM_ERROR);
    DBMS_OUTPUT.PUT_LINE('NOMBRE: '||LN_NOMCOMPLETO);
    DBMS_OUTPUT.PUT_LINE('MATRICULA'||' '||'ENTREGADO');
    FOR RC_VEHICULO IN C_VEHICULO LOOP
        DBMS_OUTPUT.PUT_LINE(RC_VEHICULO.K_MATRICULA||' '||RC_VEHICULO.I_ENTREGADO);
    END LOOP;
    SELECT V_TOTAL,V_TOTAL/(SELECT COUNT(*) FROM RESERVA_VEHICULO WHERE K_RESERVA=PK_RESERVA) INTO LV_TOTAL, LV_PROMEDIO
    FROM RESERVA
    WHERE K_RESERVA=PK_RESERVA;
    DBMS_OUTPUT.PUT_LINE('TOTAL: '||LV_TOTAL);
    DBMS_OUTPUT.PUT_LINE('PROMEDIO: '||LV_PROMEDIO);
END PR_REPORTE_RESERVAS;
/