--HEADER, COMPILAR PRIMERO
CREATE OR REPLACE PACKAGE PK_XXX
AS
	--Definición de tipos y variables g_
	--Definición de funciones y procedimientos.
	CREATE OR REPLACE PROCEDURE PR_XXX();
	CREATE OR REPLACE PROCEDURE	FU_XXX() RETURN /*TIPO*/;
END PK_XXX;

--BODY, COMPILAR SEGUNDO
CREATE OR REPLACE PACKAGE BODY PK_XXX
AS
	PROCEDURE PR_XXX();
	AS
		--
	END PR_XXX;

	PROCEDURE FU_XXX()RETURN /*TIPO*/;
	AS
		--
	END FU_XXX;
	
END PK_XXX;